# Use the official Node.js image as a base
FROM node:20.13.1

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . ./

# Expose the port the app runs on (default is 3000)
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
